area/dev/pages: 'pages'
area/dev/includes: 'includes'
area/dev/layouts: 'layouts'
area/dev/assets: 'assets'
area/dev/workflows: '(workflow|workflows)'
area/posts/adventures: '(adventures|adventure)'
area/posts/computing: 'computing'
area/posts/recipes: '(recipes|recipe)'
type/feat: 'feat'
type/fix: 'fix'
