area/dev/pages: '(pages|page)'
area/dev/includes: '(includes|include)'
area/dev/layouts: '(layouts|layout)'
area/dev/assets: '(assets|asset)'
area/dev/workflows: '(workflow|workflows)'
area/posts/adventures: '(adventures|adventure)'
area/posts/computing: 'computing'
area/posts/recipes: '(recipes|recipe)'
type/feat: 'feat'
type/fix: 'fix'
