labels:
  - name: area/dev/assets
    pattern: assets
  - name: area/dev/backend
    pattern: backend
  - name: area/dev/includes
    pattern: includes
  - name: area/dev/layouts
    pattern: layouts
  - name: area/dev/pages
    pattern: pages
  - name: area/posts/computing
    pattern: computing
  - name: area/posts/recipes
    pattern: recipes
  - name: type/feat
    pattern: feat
  - name: type/fix
    pattern: fix
