area/dev/assets:
    - '(assets)'
area/dev/backend:
    - '(backend)'
area/dev/includes:
    - '(includes)'
area/dev/layouts:
    - '(layouts)'
area/dev/pages:
    - '(pages)'
area/dev/workflow:
    - '(workflow)'
area/posts/computing:
    - '(computing)'
area/posts/recipes:
    - '(recipes)'
# Add/remove 'critical' label if issue contains the words 'feat' or 'feature'
type/feat:
    - '(feat|feature)'
type/fix:
    - '(fix)'
